FROM bde2020/spark-python-template:3.1.2-hadoop3.2

ENV SPARK_MASTER_PORT 7077
ENV SPARK_APPLICATION_PYTHON_LOCATION /app/flightDelays.py
ENV SPARK_APPLICATION_ARGS ""
ENV SPARK_SUBMIT_ARGS "--executor-memory 3G --executor-cores 3"